/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as CanteirosRouteImport } from './routes/canteiros'
import { Route as ColheitasRouteImport } from './routes/colheitas'
import { Route as CulturasRouteImport } from './routes/culturas'
import { Route as DestinacoesRouteImport } from './routes/destinacoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ParticipantesRouteImport } from './routes/participantes'
import { Route as PlantiosRouteImport } from './routes/plantios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteirosRoute = CanteirosRouteImport.update({
  id: '/canteiros',
  path: '/canteiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ColheitasRoute = ColheitasRouteImport.update({
  id: '/colheitas',
  path: '/colheitas',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturasRoute = CulturasRouteImport.update({
  id: '/culturas',
  path: '/culturas',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinacoesRoute = DestinacoesRouteImport.update({
  id: '/destinacoes',
  path: '/destinacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantesRoute = ParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantiosRoute = PlantiosRouteImport.update({
  id: '/plantios',
  path: '/plantios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/canteiros': typeof CanteirosRoute
  '/colheitas': typeof ColheitasRoute
  '/culturas': typeof CulturasRoute
  '/destinacoes': typeof DestinacoesRoute
  '/historico': typeof HistoricoRoute
  '/participantes': typeof ParticipantesRoute
  '/plantios': typeof PlantiosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/canteiros': typeof CanteirosRoute
  '/colheitas': typeof ColheitasRoute
  '/culturas': typeof CulturasRoute
  '/destinacoes': typeof DestinacoesRoute
  '/historico': typeof HistoricoRoute
  '/participantes': typeof ParticipantesRoute
  '/plantios': typeof PlantiosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/canteiros': typeof CanteirosRoute
  '/colheitas': typeof ColheitasRoute
  '/culturas': typeof CulturasRoute
  '/destinacoes': typeof DestinacoesRoute
  '/historico': typeof HistoricoRoute
  '/participantes': typeof ParticipantesRoute
  '/plantios': typeof PlantiosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/canteiros'
    | '/colheitas'
    | '/culturas'
    | '/destinacoes'
    | '/historico'
    | '/participantes'
    | '/plantios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/canteiros'
    | '/colheitas'
    | '/culturas'
    | '/destinacoes'
    | '/historico'
    | '/participantes'
    | '/plantios'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/canteiros'
    | '/colheitas'
    | '/culturas'
    | '/destinacoes'
    | '/historico'
    | '/participantes'
    | '/plantios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  CanteirosRoute: typeof CanteirosRoute
  ColheitasRoute: typeof ColheitasRoute
  CulturasRoute: typeof CulturasRoute
  DestinacoesRoute: typeof DestinacoesRoute
  HistoricoRoute: typeof HistoricoRoute
  ParticipantesRoute: typeof ParticipantesRoute
  PlantiosRoute: typeof PlantiosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteiros': {
      id: '/canteiros'
      path: '/canteiros'
      fullPath: '/canteiros'
      preLoaderRoute: typeof CanteirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colheitas': {
      id: '/colheitas'
      path: '/colheitas'
      fullPath: '/colheitas'
      preLoaderRoute: typeof ColheitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culturas': {
      id: '/culturas'
      path: '/culturas'
      fullPath: '/culturas'
      preLoaderRoute: typeof CulturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinacoes': {
      id: '/destinacoes'
      path: '/destinacoes'
      fullPath: '/destinacoes'
      preLoaderRoute: typeof DestinacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participantes': {
      id: '/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof ParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantios': {
      id: '/plantios'
      path: '/plantios'
      fullPath: '/plantios'
      preLoaderRoute: typeof PlantiosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  CanteirosRoute: CanteirosRoute,
  ColheitasRoute: ColheitasRoute,
  CulturasRoute: CulturasRoute,
  DestinacoesRoute: DestinacoesRoute,
  HistoricoRoute: HistoricoRoute,
  ParticipantesRoute: ParticipantesRoute,
  PlantiosRoute: PlantiosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
